version: '2'
services:
  web:
    build: .
    image: abibao/grav:admin
    container_name: administrator-grav-gantry-apache
    privileged: true
    ports:
      - 8686:80
    links:
      - memcached:memcached
    volumes:
      - ./html:/var/www/html
  memcached:
    image: memcached
    container_name: administrator-grav-gantry-memcached
    ports:
      - 11211:11211
