name: _offline
timestamp: 1478779799
version: 7
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1478772562
positions:
  footer: Footer
sections:
  header: Header
  main: Main
  footer: Footer
particles:
  logo:
    logo-8091: Logo
  spacer:
    spacer-7827: Spacer
    spacer-3400: Spacer
  messages:
    system-messages-8158: 'System Messages'
  content:
    system-content-4565: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-6839: Copyright
  branding:
    branding-2884: Branding
inherit: {  }
