version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1478772562
layout:
  /header/:
    -
      - 'logo-8091 30'
      - 'spacer-7827 70'
  /main/:
    -
      - system-messages-8158
    -
      - system-content-4565
  /footer/:
    -
      - position-footer
    -
      - 'copyright-6839 40'
      - 'spacer-3400 30'
      - 'branding-2884 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
