name: _body_only
timestamp: 1478779799
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1478772562
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-8554: 'System Messages'
  content:
    system-content-7657: 'Page Content'
inherit: {  }
