version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1478772562
layout:
  /header/:
    -
      - 'logo-2936 30'
      - 'spacer-5106 70'
  /navigation/:
    -
      - menu-3731
  /main/:
    -
      - system-content-2203
  /footer/:
    -
      - position-footer
    -
      - 'copyright-6353 40'
      - 'spacer-1624 30'
      - 'branding-1122 30'
  offcanvas:
    -
      - mobile-menu-8452
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
